
default: &default
  adapter:  postgresql
  host:     localhost
  username: dylan
  password: Tsukidesu1
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: device_omniauth_development

test:
  <<: *default
  database: device_omniauth_test

production:
  <<: *default
  database: device_omniauth_production
